---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: mongo
    release: primary
  name: mongo
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
