---

apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
    release: primary
spec:
  type: ClusterIP
  ports:
  - name: mongodb
    port: 27017
    targetPort: mongodb
  selector:
    app: mongo
    release: primary
